### ISSUE TITLE
[website] modification status indicator for icons

### ISSUE THREAD

**Issue by wayne-shih** [lucide-icons/lucide#169]
since this is a fork of feather icons, would be good to have some sort of indication for icon status. 

ie. whether an icon is —
(a) unchanged from feather,
(b) modified from feather, or
(c) new icon not shipped in feather. 

This could either be a standalone docs page on GH or if integrated into https://lucide.netlify.app it could be in the form of a dot or triangle 

as there's currently no changelog (that I can see), the only way to find out if icons have changed or new from feather is to compare them or go through the commit history

pros for current feather users — 
able to do a quick glance on what the new sets are; easily allow designers/devs to make the judgement call on whether or not to switch. and if so, whether icons have been modified to avoid surprises

perhaps would look something like this — 
![Frame 1](https://user-images.githubusercontent.com/51947763/104393571-a1f5b300-55a9-11eb-847c-96745cd1eb79.png)
![Frame 2](https://user-images.githubusercontent.com/51947763/104393575-a3bf7680-55a9-11eb-98cf-9e5f1f23bdd6.png)

thoughts?

**Comment by mittalyashu** [comment]
We can create a `changelog.yml` file which can work as an actual changelog for the icons and to show the status (new or modified) on icon itself.

**changelog.yaml**
```yaml
log:
  - title: "Infinity"
    icon: "infinity"
    date: 1611728108
    type: new
  - title: "Adjust the curve on edges"
    icon: "x"
    date: 1611728108
    type: modified
```
