### ISSUE TITLE
Adding color on the icon with SCSS

### ISSUE THREAD

**Issue by thomasbnt** [lucide-icons/lucide#886]
Hello, my project is in SCSS and I would like to configure the color of the icon with the parameter "color=" with variables. Like this : 

```html
<Github color="$primary-color" :size="16" />
```

It's possible?

**Comment by karsa-mistmere** [comment]
You have to use `stroke`, I believe.

**Comment by ericfennis** [comment]
I assume you're using the React Package.
I think you can accomplish to write it in your scss file:

```scss
.lucide-github {
  color: $primary-color
}
```

or if you want to do it application wide:

```scss
.lucide{
  color: $primary-color
}
```

Other solution is export you sass variables to javascript with:
```scss
/* My scss variables file*/
:export {
  primary: $primary-color
}
```
And then import sass file in you javascript file to access the variables.
